package authz

const (
	ActionGetMe                  = "me:get"
	ActionMePatch                = "me:patch"
	ActionProfileHomeGet         = "profile_home:get"
	ActionKnowledgeSearch        = "knowledge:search"
	ActionKnowledgeList          = "knowledge:list"
	ActionKnowledgeGet           = "knowledge:get"
	ActionKnowledgeCreate        = "knowledge:create"
	ActionKnowledgePatch         = "knowledge:patch"
	ActionKnowledgeDelete        = "knowledge:delete"
	ActionUsersList              = "users:list"
	ActionUsersGet               = "users:get"
	ActionUsersPatch             = "users:patch"
	ActionClassesList            = "classes:list"
	ActionClassesGet             = "classes:get"
	ActionClassesCreate          = "classes:create"
	ActionClassesPatch           = "classes:patch"
	ActionAdminLogsList          = "admin_logs:list"
	ActionFilesUpload            = "files:upload"
	ActionFilesGet               = "files:get"
	ActionFilesList              = "files:list"
	ActionFilesDelete            = "files:delete"
	ActionNotifTplCreate         = "notification:template:create"
	ActionNotifTplGet            = "notification:template:get"
	ActionNotifLogsList          = "notification:logs:list"
	ActionNotifUnreadGet         = "notification:unread:get"
	ActionAnnouncementsList      = "announcements:list"
	ActionAnnouncementsListAll   = "announcements:list:all"
	ActionAnnouncementsGet       = "announcements:get"
	ActionAnnouncementsGetAll    = "announcements:get:all"
	ActionAnnouncementsAdminList = "announcements:admin:list"
	ActionAnnouncementsAdminGet  = "announcements:admin:get"
	ActionAnnouncementsCreate    = "announcements:create"
	ActionAnnouncementsPatch     = "announcements:patch"
	ActionAnnouncementsPublish   = "announcements:publish"
	ActionAnnouncementsArchive   = "announcements:archive"
)
