#!/usr/bin/env bash

set -euo pipefail

BASE_URL="${BASE_URL:-http://127.0.0.1:8080}"
JWT_SECRET="${JWT_SECRET:-dev-secret-change-in-production}"

STUDENT_USER_ID="${STUDENT_USER_ID:-100}"
STUDENT_ROLE="${STUDENT_ROLE:-1}"
STUDENT_CLASS_ID="${STUDENT_CLASS_ID:-1}"
STUDENT_GRADE="${STUDENT_GRADE:-2023}"

ADMIN_USER_ID="${ADMIN_USER_ID:-999}"
ADMIN_ROLE="${ADMIN_ROLE:-4}"
ADMIN_CLASS_ID="${ADMIN_CLASS_ID:-1}"
ADMIN_GRADE="${ADMIN_GRADE:-2023}"

UPLOAD_FILE="${UPLOAD_FILE:-}"

for cmd in curl openssl sed mktemp; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "$cmd command not found"
    exit 1
  fi
done

generate_token() {
  local user_id="$1"
  local role="$2"
  local class_id="$3"
  local grade="$4"

  local header
  header=$(echo -n '{"alg":"HS256","typ":"JWT"}' | openssl base64 | tr -d '\n' | tr '+/' '-_' | tr -d '=')
  local payload
  payload=$(echo -n "{\"sub\":$user_id,\"role\":$role,\"class_id\":$class_id,\"grade\":\"$grade\"}" | openssl base64 | tr -d '\n' | tr '+/' '-_' | tr -d '=')
  local signature
  signature=$(echo -n "$header.$payload" | openssl dgst -sha256 -hmac "$JWT_SECRET" -binary | openssl base64 | tr -d '\n' | tr '+/' '-_' | tr -d '=')
  echo "$header.$payload.$signature"
}

assert_contains() {
  local haystack="$1"
  local needle="$2"
  local label="$3"
  if [[ "$haystack" != *"$needle"* ]]; then
    echo "[FAIL] $label: expect response contains '$needle'"
    echo "response: $haystack"
    exit 1
  fi
  echo "[PASS] $label"
}

assert_status() {
  local status="$1"
  local expected="$2"
  local label="$3"
  if [[ "$status" != "$expected" ]]; then
    echo "[FAIL] $label: expected HTTP $expected, got $status"
    exit 1
  fi
  echo "[PASS] $label"
}

STUDENT_TOKEN="$(generate_token "$STUDENT_USER_ID" "$STUDENT_ROLE" "$STUDENT_CLASS_ID" "$STUDENT_GRADE")"
ADMIN_TOKEN="$(generate_token "$ADMIN_USER_ID" "$ADMIN_ROLE" "$ADMIN_CLASS_ID" "$ADMIN_GRADE")"

tmpdir=""
cleanup() {
  if [[ -n "$tmpdir" && -d "$tmpdir" ]]; then
    rm -rf "$tmpdir"
  fi
}
trap cleanup EXIT

if [[ -z "$UPLOAD_FILE" ]]; then
  tmpdir="$(mktemp -d)"
  UPLOAD_FILE="$tmpdir/upload_demo.pdf"
  cat >"$UPLOAD_FILE" <<'EOF'
This is a dev upload test file.
Generated by scripts/dev/upload_api_curl.sh
EOF
fi

if [[ ! -f "$UPLOAD_FILE" ]]; then
  echo "UPLOAD_FILE not found: $UPLOAD_FILE"
  exit 1
fi

echo "== 1) Upload File (student) =="
upload_resp_and_code="$(
  curl -sS -w $'\n%{http_code}' -X POST "$BASE_URL/api/v1/files/upload" \
    -H "Authorization: Bearer $STUDENT_TOKEN" \
    -F "file=@$UPLOAD_FILE"
)"
upload_resp="${upload_resp_and_code%$'\n'*}"
upload_status="${upload_resp_and_code##*$'\n'}"
echo "$upload_resp"
assert_status "$upload_status" "200" "upload"
assert_contains "$upload_resp" "\"data\"" "upload data envelope"

file_id="$(sed -n 's/.*"id":[[:space:]]*\([0-9][0-9]*\).*/\1/p' <<<"$upload_resp" | head -n1)"
if [[ -z "$file_id" ]]; then
  echo "[FAIL] upload: failed to parse file id"
  exit 1
fi
echo "Uploaded file id: $file_id"
echo

echo "== 2) List Files (student) =="
list_resp_and_code="$(
  curl -sS -w $'\n%{http_code}' "$BASE_URL/api/v1/files?limit=20&offset=0" \
    -H "Authorization: Bearer $STUDENT_TOKEN"
)"
list_resp="${list_resp_and_code%$'\n'*}"
list_status="${list_resp_and_code##*$'\n'}"
echo "$list_resp"
assert_status "$list_status" "200" "list files"
assert_contains "$list_resp" "\"total\":" "list includes total"
assert_contains "$list_resp" "\"id\":$file_id" "list contains uploaded file"
echo

echo "== 3) Get File Metadata (student) =="
get_resp_and_code="$(
  curl -sS -w $'\n%{http_code}' "$BASE_URL/api/v1/files/$file_id" \
    -H "Authorization: Bearer $STUDENT_TOKEN"
)"
get_resp="${get_resp_and_code%$'\n'*}"
get_status="${get_resp_and_code##*$'\n'}"
echo "$get_resp"
assert_status "$get_status" "200" "get file metadata"
assert_contains "$get_resp" "\"id\":$file_id" "get metadata id"
echo

echo "== 4) Download File (student) =="
download_status="$(
  curl -sS -o /dev/null -w "%{http_code}" "$BASE_URL/api/v1/files/$file_id/download" \
    -H "Authorization: Bearer $STUDENT_TOKEN"
)"
assert_status "$download_status" "200" "download file"
echo

echo "== 5) Delete File As Student (expect forbidden) =="
delete_student_resp_and_code="$(
  curl -sS -w $'\n%{http_code}' -X DELETE "$BASE_URL/api/v1/files/$file_id" \
    -H "Authorization: Bearer $STUDENT_TOKEN"
)"
delete_student_resp="${delete_student_resp_and_code%$'\n'*}"
delete_student_status="${delete_student_resp_and_code##*$'\n'}"
echo "$delete_student_resp"
assert_status "$delete_student_status" "403" "student delete forbidden"
echo

echo "== 6) Delete File As Admin =="
delete_admin_resp_and_code="$(
  curl -sS -w $'\n%{http_code}' -X DELETE "$BASE_URL/api/v1/files/$file_id" \
    -H "Authorization: Bearer $ADMIN_TOKEN"
)"
delete_admin_resp="${delete_admin_resp_and_code%$'\n'*}"
delete_admin_status="${delete_admin_resp_and_code##*$'\n'}"
echo "$delete_admin_resp"
assert_status "$delete_admin_status" "200" "admin delete file"
assert_contains "$delete_admin_resp" "\"deleted\":true" "admin delete response"
echo

echo "Done."
